services:
  - type: web
    name: telegram-webhook-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7545746171:AAFsI8zRnrs0_INPxO6eFrCHKkukAs9FRmM"  # Add your bot token here or use Render's dashboard
    plan: free
